// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ofnhmnmexsilqdjgsydc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9mbmhtbm1leHNpbHFkamdzeWRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MzE4MDcsImV4cCI6MjA2MzUwNzgwN30.pjQ_927sgE5y2LL_k_jl0-deNbXoZAc1Gln0gtuGbu8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);